<script src="<?= BASE_URL ?>assets/vendors/jquery/jquery-3.5.1.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jarallax/jarallax.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jquery-appear/jquery.appear.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jquery-validate/jquery.validate.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/nouislider/nouislider.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/odometer/odometer.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/swiper/swiper.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/tiny-slider/tiny-slider.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/wnumb/wNumb.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/wow/wow.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/isotope/isotope.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/countdown/countdown.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/owl-carousel/owl.carousel.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/twentytwenty/twentytwenty.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/twentytwenty/jquery.event.move.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/bxslider/jquery.bxslider.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/bootstrap-select/js/bootstrap-select.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/vegas/vegas.min.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/jquery-ui/jquery-ui.js"></script>
<script src="<?= BASE_URL ?>assets/vendors/timepicker/timePicker.js"></script>
<script src="<?= BASE_URL ?>assets/js/moniz.js"></script>
<script src="<?= BASE_URL ?>assets/js/jQuery.style.switcher.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/lang.js"></script>
<script src="<?= BASE_URL ?>assets/js/color-switcher.js"></script>
